# Generated by Django 3.2.4 on 2022-01-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='qtyUnread',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
