# Generated by Django 3.2.4 on 2022-01-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_conversation_qtyunread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='qtyUnread',
            field=models.IntegerField(default=0),
        ),
    ]
