# Generated by Django 3.2.4 on 2022-01-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0004_alter_conversation_qtyunread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='qtyUnread',
            new_name='user1QtyUnread',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2QtyUnread',
            field=models.IntegerField(default=1),
        ),
    ]
