# Generated by Django 3.2.4 on 2022-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0005_auto_20220109_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user1QtyUnread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user2QtyUnread',
            field=models.IntegerField(default=0),
        ),
    ]
